require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bom_structures", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # BomStructure. As you add validations to BomStructure, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BomStructure.create! valid_attributes
      get bom_structures_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bom_structure = BomStructure.create! valid_attributes
      get bom_structure_url(bom_structure)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bom_structure_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      bom_structure = BomStructure.create! valid_attributes
      get edit_bom_structure_url(bom_structure)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BomStructure" do
        expect {
          post bom_structures_url, params: { bom_structure: valid_attributes }
        }.to change(BomStructure, :count).by(1)
      end

      it "redirects to the created bom_structure" do
        post bom_structures_url, params: { bom_structure: valid_attributes }
        expect(response).to redirect_to(bom_structure_url(BomStructure.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BomStructure" do
        expect {
          post bom_structures_url, params: { bom_structure: invalid_attributes }
        }.to change(BomStructure, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bom_structures_url, params: { bom_structure: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bom_structure" do
        bom_structure = BomStructure.create! valid_attributes
        patch bom_structure_url(bom_structure), params: { bom_structure: new_attributes }
        bom_structure.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bom_structure" do
        bom_structure = BomStructure.create! valid_attributes
        patch bom_structure_url(bom_structure), params: { bom_structure: new_attributes }
        bom_structure.reload
        expect(response).to redirect_to(bom_structure_url(bom_structure))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        bom_structure = BomStructure.create! valid_attributes
        patch bom_structure_url(bom_structure), params: { bom_structure: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bom_structure" do
      bom_structure = BomStructure.create! valid_attributes
      expect {
        delete bom_structure_url(bom_structure)
      }.to change(BomStructure, :count).by(-1)
    end

    it "redirects to the bom_structures list" do
      bom_structure = BomStructure.create! valid_attributes
      delete bom_structure_url(bom_structure)
      expect(response).to redirect_to(bom_structures_url)
    end
  end
end
