require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/curr_xchgs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CurrXchg. As you add validations to CurrXchg, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CurrXchg.create! valid_attributes
      get curr_xchgs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      curr_xchg = CurrXchg.create! valid_attributes
      get curr_xchg_url(curr_xchg)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_curr_xchg_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      curr_xchg = CurrXchg.create! valid_attributes
      get edit_curr_xchg_url(curr_xchg)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CurrXchg" do
        expect {
          post curr_xchgs_url, params: { curr_xchg: valid_attributes }
        }.to change(CurrXchg, :count).by(1)
      end

      it "redirects to the created curr_xchg" do
        post curr_xchgs_url, params: { curr_xchg: valid_attributes }
        expect(response).to redirect_to(curr_xchg_url(CurrXchg.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CurrXchg" do
        expect {
          post curr_xchgs_url, params: { curr_xchg: invalid_attributes }
        }.to change(CurrXchg, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post curr_xchgs_url, params: { curr_xchg: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested curr_xchg" do
        curr_xchg = CurrXchg.create! valid_attributes
        patch curr_xchg_url(curr_xchg), params: { curr_xchg: new_attributes }
        curr_xchg.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the curr_xchg" do
        curr_xchg = CurrXchg.create! valid_attributes
        patch curr_xchg_url(curr_xchg), params: { curr_xchg: new_attributes }
        curr_xchg.reload
        expect(response).to redirect_to(curr_xchg_url(curr_xchg))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        curr_xchg = CurrXchg.create! valid_attributes
        patch curr_xchg_url(curr_xchg), params: { curr_xchg: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested curr_xchg" do
      curr_xchg = CurrXchg.create! valid_attributes
      expect {
        delete curr_xchg_url(curr_xchg)
      }.to change(CurrXchg, :count).by(-1)
    end

    it "redirects to the curr_xchgs list" do
      curr_xchg = CurrXchg.create! valid_attributes
      delete curr_xchg_url(curr_xchg)
      expect(response).to redirect_to(curr_xchgs_url)
    end
  end
end
